/*
BASE DE DATOS: aurkitu
SCHEMA: public
*/

-- Se añade la extensión PostGIS si la base de datos no la traía preinstalada
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. FUNCIONES (Para Triggers)
-- Esta función actualiza la fecha de modificación automáticamente
CREATE OR REPLACE FUNCTION public.trigger_actualizar_last_update_date()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_update_date = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Tabla para almacenar los tipos de objetos perdidos más habituales
CREATE TABLE public.tipo_objeto(
    id int GENERATED BY DEFAULT AS IDENTITY,
    codigo text NOT NULL, -- código para el front 
    CONSTRAINT tipo_objeto_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_objeto_codigo_key UNIQUE (codigo)
);

-- Tabla para almacenar los colores más habituales
CREATE TABLE public.color(
    id int GENERATED BY DEFAULT AS IDENTITY,
    codigo text NOT NULL,
    CONSTRAINT color_pkey PRIMARY KEY (id),
    CONSTRAINT color_codigo_key UNIQUE (codigo)
);

-- Se crean las tablas lookup para idioma, tipos de objeto
CREATE TABLE public.idioma(
    codigo varchar(5) NOT NULL,
    nombre text NOT NULL,
    CONSTRAINT idioma_pkey PRIMARY KEY (codigo)
);

-- Se rellena con los idiomas más habituales
INSERT INTO public.idioma(codigo, nombre) VALUES
('es', 'castellano'),
('eu', 'euskera'),
('en', 'ingles');


INSERT INTO public.tipo_objeto(id, codigo) VALUES
(0, 'desconocido'),
(1, 'smartphone'),
(2, 'auriculares'),
(3, 'bolso'),
(4, 'cartera'),
(5, 'llaves'),
(6, 'gafas'),
(7, 'paraguas'),
(8, 'documentacion'),
(9, 'prenda'),
(10, 'otros');


INSERT INTO public.color(id, codigo) VALUES
(0, 'desconocido'),
(1, 'amarillo'),
(2, 'negro'),
(3, 'blanco'),
(4, 'rojo'),
(5, 'azul'),
(6, 'verde'),
(7, 'naranja'),
(8, 'gris'),
(9, 'marron'),
(10, 'otros');

-- Tipo enum para estados del objeto
CREATE TYPE public.estado_objeto AS ENUM (
    'perdido',
    'encontrado',
    'devuelto'
);

-- Tablas para usarios
CREATE TABLE public.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) NOT NULL,
    hashed_password text NOT NULL,
    email varchar(100) NOT NULL,
    idioma_codigo varchar(5) NOT NULL DEFAULT 'es',
    verificado bool NOT NULL DEFAULT false,
    create_date timestamptz NOT NULL DEFAULT now(),
    last_update_date timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email),
    CONSTRAINT usuario_username_key UNIQUE (username)
);

-- Tabla para proceso de alta de usuario con códigos
CREATE TABLE public.codigos_verificacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NULL,
    code varchar(6) NOT NULL,
    create_date timestamptz NOT NULL DEFAULT now(),
    expiration_date timestamptz NOT NULL,
    CONSTRAINT codigos_verificacion_pkey PRIMARY KEY (id)
);

--Refresh tokens para JWT
CREATE TABLE public.refresh_token(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    hashed_token varchar(255) NOT NULL,
    create_date timestamptz NOT NULL DEFAULT now(),
    expiration_date timestamptz NOT NULL,
    CONSTRAINT refresh_token_hashed_token_key UNIQUE (hashed_token),
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
);

--Tabla de objetos
CREATE TABLE public.objeto(
    id bigint GENERATED BY DEFAULT AS IDENTITY, 
    estado public.estado_objeto NOT NULL DEFAULT 'perdido',   
    user_id bigint NOT NULL,
    ubicacion geography(Point, 4326) NOT NULL,
    radio_metros int NOT NULL DEFAULT 0,
    tipo int NOT NULL DEFAULT 0,
    descripcion text NOT NULL,
    marca text NULL,
    numero_serie text NULL,
    color int NOT NULL default 0,
    foto_url text NULL,
    factura_url text NULL,
    fecha_perdida timestamptz NOT NULL DEFAULT now(),
    create_date timestamptz NOT NULL DEFAULT now(),
    last_update_date timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT objeto_pkey PRIMARY KEY (id),
    CONSTRAINT objeto_descripcion_check CHECK (length(descripcion) > 0)    
);

-- Mensajes
CREATE TABLE public.mensaje (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    remitente_id bigint NOT NULL,
    destinatario_id bigint NOT NULL,
    objeto_id bigint NOT NULL,
    contenido text NOT NULL,
    leido BOOLEAN NOT NULL DEFAULT false,
    create_date timestamptz NOT NULL DEFAULT now(),
    last_update_date timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT mensaje_pkey PRIMARY KEY (id),
    CONSTRAINT mensaje_contenido_check CHECK (length(contenido) > 0)
);

--Foreign keys: el equipo de backend prefiere no usar borrados en cascada
--Foreign keys de public.codigos_verificacion
ALTER TABLE public.codigos_verificacion
ADD CONSTRAINT codigos_verificacion_user_id_fkey 
    FOREIGN KEY (user_id)
    REFERENCES public.usuario (id);

-- FOREIGN KEYS de la tabla usuario
ALTER TABLE public.usuario 
ADD CONSTRAINT usuario_idioma_codigo_fkey 
    FOREIGN KEY (idioma_codigo) 
    REFERENCES public.idioma (codigo) 
    ON DELETE NO ACTION;

--FK de los refresh tokens
ALTER TABLE public.refresh_token
ADD CONSTRAINT refresh_token_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.usuario (id);

--FOREIGN KEYS de objetos
ALTER TABLE public.objeto
ADD CONSTRAINT objeto_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.usuario (id)
    ON DELETE NO ACTION;

ALTER TABLE public.objeto
ADD CONSTRAINT objeto_tipo_fkey
    FOREIGN KEY (tipo)
    REFERENCES public.tipo_objeto (id)
    ON DELETE NO ACTION;

ALTER TABLE public.objeto
ADD CONSTRAINT objeto_color_fkey
    FOREIGN KEY (color)
    REFERENCES public.color (id)
    ON DELETE NO ACTION;

--Foreign keys de los mensajes
ALTER TABLE public.mensaje ADD CONSTRAINT mensaje_remitente_id_fkey FOREIGN KEY (remitente_id) REFERENCES public.usuario (id) ON DELETE NO ACTION;
ALTER TABLE public.mensaje ADD CONSTRAINT mensaje_destinatario_id_fkey FOREIGN KEY (destinatario_id) REFERENCES public.usuario (id) ON DELETE NO ACTION;
ALTER TABLE public.mensaje ADD CONSTRAINT mensaje_objeto_id_fkey FOREIGN KEY (objeto_id) REFERENCES public.objeto (id) ON DELETE NO ACTION;

-- Tirggers para la fecha de modificacion
CREATE TRIGGER trigger_usuario_modificacion
BEFORE UPDATE ON public.usuario
FOR EACH ROW EXECUTE FUNCTION public.trigger_actualizar_last_update_date();

CREATE TRIGGER trigger_objeto_modificacion
BEFORE UPDATE ON public.objeto
FOR EACH ROW EXECUTE FUNCTION public.trigger_actualizar_last_update_date();

CREATE TRIGGER trigger_mensaje_modificacion
BEFORE UPDATE ON public.mensaje
FOR EACH ROW EXECUTE FUNCTION public.trigger_actualizar_last_update_date();


-- INDICES - para las consultas de la funcionalidad mínima
CREATE INDEX codigos_verificacion_user_id_idx ON public.codigos_verificacion (user_id);
CREATE INDEX objeto_user_id_idx ON public.objeto (user_id);
CREATE INDEX objeto_ubicacion_gix ON public.objeto USING GiST (ubicacion);
CREATE INDEX mensaje_destinatario_id_idx ON public.mensaje (destinatario_id);
CREATE INDEX refresh_token_user_id_idx ON public.refresh_token (user_id);
