/* Nueva tabla en BD de conversaciones (mensajes entre los mismos usuarios sobre un objeto)
 - Crea tabla conversacion
 - Refactoriza tabla mensaje (elimina destinatario/objeto, añade conversacion_id)
 - Añade triggers de actualización automática */

-- 1. Crear la tabla 'conversacion'
CREATE TABLE public.conversacion (
     id bigint GENERATED BY DEFAULT AS IDENTITY,
     objeto_id bigint NOT NULL,
     participante1_id bigint NOT NULL,
     participante2_id bigint NOT NULL,
     create_date timestamptz NOT NULL DEFAULT now(),
     last_update_date timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT conversacion_pkey PRIMARY KEY (id),
     CONSTRAINT conversacion_unica_1obj_2user UNIQUE (objeto_id, participante1_id, participante2_id)
);

-- Foreign Keys de Conversacion
ALTER TABLE public.conversacion ADD CONSTRAINT conversacion_objeto_fkey FOREIGN KEY (objeto_id) REFERENCES public.objeto (id) ON DELETE NO ACTION;
ALTER TABLE public.conversacion ADD CONSTRAINT conversacion_part1_fkey FOREIGN KEY (participante1_id) REFERENCES public.usuario (id) ON DELETE NO ACTION;
ALTER TABLE public.conversacion ADD CONSTRAINT conversacion_part2_fkey FOREIGN KEY (participante2_id) REFERENCES public.usuario (id) ON DELETE NO ACTION;

-- Trigger para actualizar last_update_date en conversacion
CREATE TRIGGER trigger_conversacion_modificacion
BEFORE UPDATE ON public.conversacion
FOR EACH ROW EXECUTE FUNCTION public.trigger_actualizar_last_update_date();

-- Índice para buscar conversaciones de un ususario rápidamente
CREATE INDEX conversacion_participante1_id_idx ON public.conversacion (participante1_id);
CREATE INDEX conversacion_participante2_id_idx ON public.conversacion (participante2_id);

-- 2. MODIFICAR TABLA MENSAJE (Refactorización)
-- Quitaremos las columnas destinatario_id y objeto_id, porque se obtienen desde la conversación
-- Primero eliminamos las restricciones (Foreign Keys) antiguas
ALTER TABLE public.mensaje DROP CONSTRAINT mensaje_destinatario_id_fkey;
ALTER TABLE public.mensaje DROP CONSTRAINT mensaje_objeto_id_fkey;
--Índice creado lo eliminamos
DROP INDEX IF EXISTS mensaje_destinatario_id_idx;

-- Eliminamos las columnas redundantes
ALTER TABLE public.mensaje DROP COLUMN destinatario_id;
ALTER TABLE public.mensaje DROP COLUMN objeto_id;

-- Añadimos la columna de enlace a la conversación (está la tabla vacía)
ALTER TABLE public.mensaje ADD COLUMN conversacion_id bigint NOT NULL;

-- Añadimos la nueva Foreign Key
ALTER TABLE public.mensaje ADD CONSTRAINT mensaje_conversacion_fkey FOREIGN KEY (conversacion_id) REFERENCES public.conversacion(id) ON DELETE NO ACTION;

-- Índice para buscar mensajes por conversación rápidamente
CREATE INDEX mensaje_conversacion_id_idx ON public.mensaje (conversacion_id);


