# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aurkitu?ssl=false&sslmode=disable
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASS}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Colores para consola 
spring.output.ansi.enabled=ALWAYS

# Enviar mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAILUSER}
spring.mail.password=${MAILPASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
eus.birt.proyecto.jwtSecret=${JWTSECRET}
eus.birt.proyecto.jwtAccessExpirationMs=900000
eus.birt.proyecto.jwtRefreshExpirationMs=604800000